syntax = "proto3";

package queue;
import "google/protobuf/timestamp.proto";

service Queue{
    rpc Enqueue(EnqueueRequest) returns (EnqueueResponse);
    rpc Dequeue(DequeueRequest) returns (DequeueResponse);
    rpc Ack(AckRequest) returns (AckResponse);
}

message EnqueueRequest {
    string payload = 1;
}

message EnqueueResponse {
  string job_id = 1;
}

message DequeueRequest {}

message DequeueResponse {
    optional string job_id = 1;
    optional string delivery_id = 2;
    optional string payload = 3;
    optional google.protobuf.Timestamp created_at = 4;

}

message AckRequest {
  string delivery_id = 1;
}
message AckResponse {}